-- DROP USER PARKING CASCADE;

CREATE USER PARKING IDENTIFIED BY "GG##lab12345";
GRANT CONNECT, RESOURCE TO PARKING;
GRANT UNLIMITED TABLESPACE TO PARKING;

CREATE TABLE "PARKING"."CITIES" 
   (	"CITYID" VARCHAR2(3 BYTE) COLLATE "USING_NLS_COMP", 
	"CITY" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"COUNTRYID" VARCHAR2(3 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  
CREATE TABLE "PARKING"."COUNTRIES" 
   (	"COUNTRYID" VARCHAR2(3 BYTE) COLLATE "USING_NLS_COMP", 
	"COUNTRY" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP", 
	"REGIONID" NUMBER(*,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  
CREATE TABLE "PARKING"."PARKINGDATA" 
   (	"PARKINGDATAID" NUMBER(18,0), 
	"PARKINGID" VARCHAR2(12 BYTE) COLLATE "USING_NLS_COMP", 
	"CARREGID" VARCHAR2(12 BYTE) COLLATE "USING_NLS_COMP", 
	"INTIME" DATE, 
	"OUTTIME" DATE, 
	"PARKINGRATE" FLOAT(126)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

CREATE TABLE "PARKING"."PARKINGS" 
   (	"PARKINGID" VARCHAR2(12 BYTE) COLLATE "USING_NLS_COMP", 
	"PARKINGNAME" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"AVAILABLESLOT" NUMBER(*,0), 
	"COUNTRYID" VARCHAR2(3 BYTE) COLLATE "USING_NLS_COMP", 
	"CITYID" VARCHAR2(3 BYTE) COLLATE "USING_NLS_COMP", 
	"STREETADDRESS" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP", 
	"LONGITUDE" FLOAT(126), 
	"LATITUDE" FLOAT(126)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

CREATE TABLE "PARKING"."PAYMENTDATA" 
   (	"TRANSACTIONID" VARCHAR2(24 BYTE) COLLATE "USING_NLS_COMP", 
	"TRANSACTIONAMOUNT" FLOAT(126), 
	"TRANSACTIONMETHOD" VARCHAR2(8 BYTE) COLLATE "USING_NLS_COMP", 
	"PARKINGDATAID" NUMBER(18,0), 
	"PARKINGID" VARCHAR2(12 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  
--------------------------------------------------------
--  DDL for Index CITIES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PARKING"."CITIES_PK" ON "PARKING"."CITIES" ("CITYID", "COUNTRYID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table CITIES
--------------------------------------------------------

  ALTER TABLE "PARKING"."CITIES" ADD CONSTRAINT "CITIES_PK" PRIMARY KEY ("CITYID", "COUNTRYID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  
  --------------------------------------------------------
--  DDL for Index COUNTRIES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PARKING"."COUNTRIES_PK" ON "PARKING"."COUNTRIES" ("COUNTRYID", "COUNTRY") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table COUNTRIES
--------------------------------------------------------

  ALTER TABLE "PARKING"."COUNTRIES" ADD CONSTRAINT "COUNTRIES_PK" PRIMARY KEY ("COUNTRYID", "COUNTRY")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;

--------------------------------------------------------
--  DDL for Index PARKINGDATA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PARKING"."PARKINGDATA_PK" ON "PARKING"."PARKINGDATA" ("PARKINGDATAID", "PARKINGID", "CARREGID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table PARKINGDATA
--------------------------------------------------------

  ALTER TABLE "PARKING"."PARKINGDATA" ADD CONSTRAINT "PARKINGDATA_PK" PRIMARY KEY ("PARKINGDATAID", "PARKINGID", "CARREGID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;

--------------------------------------------------------
--  DDL for Index PARKINGS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PARKING"."PARKINGS_PK" ON "PARKING"."PARKINGS" ("PARKINGID", "PARKINGNAME") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table PARKINGS
--------------------------------------------------------

  ALTER TABLE "PARKING"."PARKINGS" ADD CONSTRAINT "PARKINGS_PK" PRIMARY KEY ("PARKINGID", "PARKINGNAME")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;

--------------------------------------------------------
--  DDL for Index PAYMENTDATA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PARKING"."PAYMENTDATA_PK" ON "PARKING"."PAYMENTDATA" ("TRANSACTIONID", "PARKINGID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table PAYMENTDATA
--------------------------------------------------------

  ALTER TABLE "PARKING"."PAYMENTDATA" ADD CONSTRAINT "PAYMENTDATA_PK" PRIMARY KEY ("TRANSACTIONID", "PARKINGID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;

BEGIN
 ords_admin.enable_schema(
  p_enabled => TRUE,
  p_schema => 'parking',
  p_url_mapping_type => 'BASE_PATH',
  p_url_mapping_pattern => 'parking',
  p_auto_rest_auth => NULL
 );
 commit;
END;